@Book_Library_API_HostAddress = http://localhost:5265

POST {{Book_Library_API_HostAddress}}/api/books
Content-Type: application/json

{
  "title": "The Brothers Karamazov",
  "author": "Fyodor Dostoevsky",
  "pages": 796,
  "year": 1879
}